### ISSUE TITLE
lucky 13 whitepaper broken link 

### ISSUE THREAD

**Issue by gellge** [lenny233/awesome-tls-hacks#1]
Hey! thanks for this repo, good references are always a blessing. I visited the [Lucky 13 whitepaper link](http://isg.rhul.ac.uk/tls/TLStiming.pdf) and noticed it returns 404 (upgrading it to https did not do the trick).
The whitepaper itself can be found on [Web Archive](http://web.archive.org/web/20190323053131/https://isg.rhul.ac.uk/tls/TLStiming.pdf).
Do you think we could update the link to the archived copy? Or just upload a copy of the whitepaper to this repo and link directly to that? If you would like, I might go over the other links of the repo and see if they are in need of a refresh as well.

g

**Comment by lennysec** [comment]
Hi Giacomo,
Thanks for your feedback.  

This issue was fixed in https://github.com/lennysec/awesome-tls-hacks/commit/cd69e1bc32e0d5fb20e5b7b738f608aa030ce2f4
I found this paper was available for free on the IEEE website, so I used the PDF file link on this page：
https://ieeexplore.ieee.org/abstract/document/6547131

Feel free to open an issue or submit a PR.

**Comment by lennysec** [comment]
btw, I've checked all the links and fixed the broken ones.
Thanks for reminding me of this.

**Comment by gellge** [comment]
No problem, good that you found a fresh link!
